name: secret

on: push

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: print var
        run: echo "The secret is \${{ secrets.SECRET }}"
      - name: print var2
        run: echo "The secret is ${{ secrets.SECRET }}"
